[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRMS", "Cost/Freemium"]
org = "ballerinax"
name = "brex.team"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
