[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Blogs", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.blogger"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
