openapi: 3.0.0
info:
  x-ballerina-display:
      label: Azure OpenAI Embeddings
      iconPath: "icon.png"
  title: Azure OpenAI Service API
  description: >
    This is the [Azure OpenAI Embeddings API v2023-03-15-preview](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#embeddings/) OpenAPI specification.
    The Azure Azure OpenAI Service REST API Embeddings Endpoint will generate one a vector representation of a given input that can be easily consumed by machine learning models and other algorithms.
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.
    Create an [Azure](https://azure.microsoft.com/en-us/features/azure-portal/) account, an [Azure OpenAI resource with a model deployed](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/create-resource) and refer [this guide](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/reference#authentication) to learn how to generate and use tokens
  version: 2023-03-15-preview
servers:
  - url: https://{endpoint}/openai
    variables:
      endpoint:
        default: your-resource-name.openai.azure.com
security:
  - bearer:
      - api.read
  - apiKey: []
paths:
  /deployments/{deployment-id}/embeddings:
    post:
      x-ballerina-display:
        label: Generate Embeddings
      summary: Get a vector representation of a given input that can be easily consumed by machine learning models and algorithms.
      operationId: embeddings_create
      parameters:
        - in: path
          name: deployment-id
          required: true
          schema:
            type: string
            example: ada-search-index-v1
          description: The deployment id of the model which was deployed.
        - in: query
          name: api-version
          required: true
          schema:
            type: string
            example: 2023-03-15-preview
            description: api version
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
              properties:
                input:
                  description: |-
                    Input text to get embeddings for, encoded as a string. To get embeddings for multiple inputs in a single request, pass an array of strings. Each input must not exceed 2048 tokens in length.
                    Unless you are embedding code, we suggest replacing newlines (\n) in your input with a single space, as we have observed inferior results when newlines are present.
                  oneOf:
                    - type: string
                      default: ''
                      example: This is a test.
                      nullable: true
                    - type: array
                      minItems: 1
                      maxItems: 2048
                      items:
                        type: string
                        minLength: 1
                        example: This is a test.
                        nullable: false
                user:
                  description: A unique identifier representing your end-user, which can help monitoring and detecting abuse.
                  type: string
                  nullable: false
                input_type:
                  description: input type of embedding search to use
                  type: string
                  example: query
                model:
                  type: string
                  description: ID of the model to use. You can use the Models_List operation to see all of your available models, or see our Models_Get overview for descriptions of them.
                  nullable: false
              required:
                - input
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  object:
                    type: string
                  model:
                    type: string
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        index:
                          type: integer
                        object:
                          type: string
                        embedding:
                          type: array
                          items:
                            type: number
                      required:
                        - index
                        - object
                        - embedding
                  usage:
                    type: object
                    properties:
                      prompt_tokens:
                        type: integer
                      total_tokens:
                        type: integer
                    required:
                      - prompt_tokens
                      - total_tokens
                required:
                  - object
                  - model
                  - data
                  - usage
components:
  schemas:
    errorResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
            message:
              type: string
            param:
              type: string
            type:
              type: string
  securitySchemes:
    bearer:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          scopes: {}
      x-tokenInfoFunc: api.middleware.auth.bearer_auth
      x-scopeValidateFunc: api.middleware.auth.validate_scopes
    apiKey:
      type: apiKey
      description: The key used to access the OpenAI APIs
      name: api-key
      in: header
