[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Product Management", "Cost/Paid"]
org = "ballerinax"
name = "prodpad"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
