[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Freemium"]
org = "ballerinax"
name = "ebay.logistics"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
