[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid"]
org = "ballerinax"
name = "sap.fieldglass.approval"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]
icon = "icon.png"

[build-options]
observabilityIncluded = true
