[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Debug Tools", "Cost/Paid"]
org = "ballerinax"
name = "elmah"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
