[package]
license = ["Apache-2.0"]
keywords = ["spotify", "spotify playlist"]
org = "ballerinax"
name = "spotify"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.2.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
