[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Marketing Automation", "Cost/Freemium"]
org = "ballerinax"
name = "sendgrid"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
