[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Browser Tools", "Cost/Freemium"]
org = "ballerinax"
name = "extpose"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
