[package]
license = ["Apache-2.0"]
keywords = ["Vonage", "Numbers"]
org = "ballerinax"
name = "vonage.numbers"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.2-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
