[package]
license = ["Apache-2.0"]
keywords = ["open weather map", "weather data", "weather forecast"]
org = "ballerinax"
name = "openweathermap"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.6.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
