[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Freemium"]
org = "ballerinax"
name = "cloudmersive.security"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
