openapi: 3.0.1
info:
  x-ballerina-display:
    label: Cloudmersive Security
    iconPath: "resources/cloudmersive.security.svg"
  title: securityapi
  description: This is a generated connector from [Cloudmersive](https://account.cloudmersive.com) OpenAPI specification.
  
    The Cloudmersive Security APIs help you detect and block security threats.
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials.

    Create a [Cloudmersive account](https://account.cloudmersive.com/login) and obtain tokens following [this guide](https://account.cloudmersive.com/keys).
  version: v1
servers:
- url: https://testapi.cloudmersive.com/
paths:
  /security/threat-detection/content/automatic/detect/string:
    post:
      tags:
      - ContentThreatDetection
      summary: Automatically detect threats in an input string
      description: Auto-detects a wide range of threat types in input string, including
        Cross-Site Scripting (XSS), SQL Injection (SQLI), XML External Entitites (XXE),
        Server-side Request Forgeries (SSRF), and JSON Insecure Deserialization (JID).
      operationId: Content Threat Detection_Automatic Threat Detection String
      requestBody:
        description: User-facing text input.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringAutomaticThreatDetection'
            text/json:
              schema:
                $ref: '#/components/schemas/StringAutomaticThreatDetection'
            application/xml:
              schema:
                $ref: '#/components/schemas/StringAutomaticThreatDetection'
            text/xml:
              schema:
                $ref: '#/components/schemas/StringAutomaticThreatDetection'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/content/insecure-deserialization/json/detect/string:
    post:
      tags:
      - ContentThreatDetection
      summary: Detect Insecure Deserialization JSON (JID) attacks in a string
      description: Detects Insecure Deserialization JSON (JID) attacks from text input.
      operationId: Content Threat Detection_Detect Insecure Deserialization Json String
      requestBody:
        description: User-facing text input.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringInsecureDeserializationJsonDetection'
            text/json:
              schema:
                $ref: '#/components/schemas/StringInsecureDeserializationJsonDetection'
            application/xml:
              schema:
                $ref: '#/components/schemas/StringInsecureDeserializationJsonDetection'
            text/xml:
              schema:
                $ref: '#/components/schemas/StringInsecureDeserializationJsonDetection'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/content/sql-injection/detect/string:
    post:
      tags:
      - ContentThreatDetection
      summary: Check text input for SQL Injection (SQLI) attacks
      description: Detects SQL Injection (SQLI) attacks from text input.
      operationId: Content Threat Detection_Check Sql Injection String
      requestBody:
        description: User-facing text input.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringSqlInjectionDetectionResult'
            text/json:
              schema:
                $ref: '#/components/schemas/StringSqlInjectionDetectionResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/StringSqlInjectionDetectionResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/StringSqlInjectionDetectionResult'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/content/xss/detect/string:
    post:
      tags:
      - ContentThreatDetection
      summary: Protect text input from Cross-Site-Scripting (XSS) attacks through
        normalization
      description: Detects and removes XSS (Cross-Site-Scripting) attacks from text
        input through normalization.  Returns the normalized result, as well as information
        on whether the original input contained an XSS risk.
      operationId: Content Threat Detection_Protect Xss
      requestBody:
        description: User-facing text input.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringXssProtectionResult'
            text/json:
              schema:
                $ref: '#/components/schemas/StringXssProtectionResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/StringXssProtectionResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/StringXssProtectionResult'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/content/xxe/detect/xml/string:
    post:
      tags:
      - ContentThreatDetection
      summary: Protect text input from XML External Entity (XXE) attacks
      description: Detects XXE (XML External Entity) attacks from XML text input.
      operationId: Content Threat Detection_Check Xxe
      requestBody:
        description: User-facing text input.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringXxeDetectionResult'
            text/json:
              schema:
                $ref: '#/components/schemas/StringXxeDetectionResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/StringXxeDetectionResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/StringXxeDetectionResult'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/network/url/ssrf/detect:
    post:
      tags:
      - NetworkThreatDetection
      summary: Check a URL for Server-side Request Forgery (SSRF) threats
      description: Checks if an input URL is at risk of being an SSRF (Server-side
        request forgery) threat or attack.
      operationId: Network Threat Detection_Detect Ssrf Url
      requestBody:
        description: Input URL request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlSsrfThreatDetectionRequestFull'
          text/json:
            schema:
              $ref: '#/components/schemas/UrlSsrfThreatDetectionRequestFull'
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UrlSsrfThreatDetectionResponseFull'
            text/json:
              schema:
                $ref: '#/components/schemas/UrlSsrfThreatDetectionResponseFull'
            application/xml:
              schema:
                $ref: '#/components/schemas/UrlSsrfThreatDetectionResponseFull'
            text/xml:
              schema:
                $ref: '#/components/schemas/UrlSsrfThreatDetectionResponseFull'
      security:
      - Apikey: []
      x-codegen-request-body-name: request
  /security/threat-detection/network/ip/is-threat:
    post:
      tags:
      - NetworkThreatDetection
      summary: Check if IP address is a known threat
      description: Check if the input IP address is a known threat IP address.  Checks
        against known bad IPs, botnets, compromised servers, and other lists of threats.
      operationId: Network Threat Detection_Is Threat
      requestBody:
        description: IP address to check, e.g. "55.55.55.55".  The input is a string
          so be sure to enclose it in double-quotes.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IPThreatDetectionResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/IPThreatDetectionResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/IPThreatDetectionResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/IPThreatDetectionResponse'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/network/ip/is-bot:
    post:
      tags:
      - NetworkThreatDetection
      summary: Check if IP address is a Bot client threat
      description: Check if the input IP address is a Bot, robot, or otherwise a non-user
        entity.  Leverages real-time signals to check against known high-probability
        bots..
      operationId: Network Threat Detection_Is Bot
      requestBody:
        description: IP address to check, e.g. "55.55.55.55".  The input is a string
          so be sure to enclose it in double-quotes.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatDetectionBotCheckResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ThreatDetectionBotCheckResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ThreatDetectionBotCheckResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/ThreatDetectionBotCheckResponse'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
  /security/threat-detection/network/ip/is-tor-node:
    post:
      tags:
      - NetworkThreatDetection
      summary: Check if IP address is a Tor node server
      description: Check if the input IP address is a Tor exit node server.  Tor servers
        are a type of privacy-preserving technology that can hide the original IP
        address who makes a request.
      operationId: Network Threat Detection_Is Tor Node
      requestBody:
        description: IP address to check, e.g. "55.55.55.55".  The input is a string
          so be sure to enclose it in double-quotes.
        content:
          application/json:
            schema:
              type: string
          text/json:
            schema:
              type: string
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreatDetectionTorNodeResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/ThreatDetectionTorNodeResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ThreatDetectionTorNodeResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/ThreatDetectionTorNodeResponse'
      security:
      - Apikey: []
      x-codegen-request-body-name: value
components:
  schemas:
    StringAutomaticThreatDetection:
      type: object
      properties:
        Successful:
          type: boolean
          description: True if the operation was successful, false otherwise
        CleanResult:
          type: boolean
        ContainedJsonInsecureDeserializationAttack:
          type: boolean
          description: True if the input contained Insecure Deserialization JSON,
            false otherwise
        ContainedXssThreat:
          type: boolean
          description: True if the input contained XSS attack, false otherwise
        ContainedXxeThreat:
          type: boolean
          description: True if the input contained XXE attack, false otherwise
        ContainedSqlInjectionThreat:
          type: boolean
          description: True if the input contained SQL Injection attack, false otherwise
        ContainedSsrfThreat:
          type: boolean
          description: True if the input contained an Server-Side Request Forgery
            (SSRF) URL attack, false otherwise
        IsXML:
          type: boolean
          description: True if the input string is XML, false otherwise
        IsJSON:
          type: boolean
          description: True if the input string is JSON, false otherwise
        IsURL:
          type: boolean
          description: True if the input string is a URL, false otherwise
        OriginalInput:
          type: string
          description: Original input string
      description: Result of performing an Insecure Deserialization JSON protection
        operation
    StringInsecureDeserializationJsonDetection:
      type: object
      properties:
        Successful:
          type: boolean
          description: True if the operation was successful, false otherwise
        ContainedJsonInsecureDeserializationAttack:
          type: boolean
          description: True if the input contained Insecure Deserialization JSON,
            false otherwise
        OriginalInput:
          type: string
          description: Original input string
      description: Result of performing an Insecure Deserialization JSON protection
        operation
    StringSqlInjectionDetectionResult:
      type: object
      properties:
        Successful:
          type: boolean
          description: True if the operation was successful, false otherwise
        ContainedSqlInjectionAttack:
          type: boolean
          description: True if the input contained SQL Injection attacks, false otherwise
        OriginalInput:
          type: string
          description: Original input string
      description: Result of performing an SQL Injection protection operation
    StringXssProtectionResult:
      type: object
      properties:
        Successful:
          type: boolean
          description: True if the operation was successful, false otherwise
        ContainedXss:
          type: boolean
          description: True if the input contained XSS scripting, false otherwise
        OriginalInput:
          type: string
          description: Original input string
        NormalizedResult:
          type: string
          description: Normalized string result, with XSS removed
      description: Result of performing an XSS protection operation
    StringXxeDetectionResult:
      type: object
      properties:
        Successful:
          type: boolean
          description: True if the operation was successful, false otherwise
        ContainedXxe:
          type: boolean
          description: True if the input contained XXE threats, false otherwise
      description: Result of performing an XXE threat detection operation
    UrlSsrfThreatDetectionRequestFull:
      type: object
      properties:
        URL:
          type: string
          description: URL to validate
        BlockedDomains:
          type: array
          description: Top level domains that you do not want to allow access to,
            e.g. mydomain.com - will block all subdomains as well
          items:
            type: string
      description: Request to determine if a URL is an SSRF threat check
    UrlSsrfThreatDetectionResponseFull:
      type: object
      properties:
        CleanURL:
          type: boolean
          description: True if the URL is clean, false if it is at risk of containing
            an SSRF threat or attack
        ThreatLevel:
          type: string
          description: Threat level of the URL; possible values are High, Medium,
            Low and None
      description: Result of checking a URL for SSRF threats
    IPThreatDetectionResponse:
      type: object
      properties:
        IsThreat:
          type: boolean
          description: True if the input IP address is a threat, false otherwise
        ThreatType:
          type: string
          description: Specifies the type of IP threat; possible values include Blocklist,
            Botnet, WebBot
      description: Result of performing a IP threat check on an IP address
    ThreatDetectionBotCheckResponse:
      type: object
      properties:
        IsBot:
          type: boolean
          description: True if the input IP address is a Bot or Robot, false otherwise
      description: Result of performing a Bot check on an IP address
    ThreatDetectionTorNodeResponse:
      type: object
      properties:
        IsTorNode:
          type: boolean
          description: True if the input IP address is a Tor exit node, false otherwise
      description: Result of performing a Tor node check on an IP address
  securitySchemes:
    Apikey:
      type: apiKey
      description: Represents API Key `Apikey`
      name: Apikey
      in: header
