[package]
license = ["Apache-2.0"]
keywords = ["Support//Customer Support", "Cost/Freemium"]
org = "ballerinax"
name = "jira.servicemanagement"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
