[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Images & Design", "Cost/Freemium"]
org = "ballerinax"
name = "opendesign"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
