[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/File Management & Storage", "Cost/Free"]
org = "ballerinax"
name = "dropbox"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
