[package]
org = "ballerinax"
name = "ronin"
icon = "icon.png"
version = "1.0.0"
distribution = "slbeta3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Finance/Billing","Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
