[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Freemium"]
org = "ballerinax"
name = "plaid"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
