[package]
org = "ballerinax"
name = "iris.esignature"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["crm","paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
