[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.oauth2"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true
