[package]
distribution = "slbeta6"
org = "ballerinax"
name = "shortcut"
icon = "icon.png"
version = "1.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Productivity/Project Management","Cost/Freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
