[package]
license = ["Apache-2.0"]
keywords = ["Finance/Accounting", "Cost/Paid"]
org = "ballerinax"
name = "xero.accounts"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
