[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Marketing/Marketing Automation", "Cost/Freemium"]
org = "ballerinax"
name = "hubspot.marketing"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
