[package]
org = "ballerinax"
name = "zuora.revenue"
version = "1.0.0"
icon = "icon.png"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Finance/Accounting","Cost/Paid"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors" 
