[package]
license = ["Apache-2.0"]
keywords = ["LeanIX", "LeanIX Integration API"]
org = "ballerinax"
name = "leanix.integrationapi"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
