[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid"]
org = "ballerinax"
name = "commercetools.configuration"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
