[package]
license = ["Apache-2.0"]
keywords = ["AI/Text", "OpenAI", "Cost/Paid", "Completions", "GPT-3", "GPT3.5", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.text"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/openai.text"
version = "1.0.3"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
