[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Scheduling & Booking", "Cost/Freemium"]
org = "ballerinax"
name = "impala"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/impala"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
