[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Video & Audio", "Cost/Freemium"]
org = "ballerinax"
name = "soundcloud"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
