[package]
license = ["Apache-2.0"]
keywords = ["Communication/Call & SMS", "Cost/Paid"]
org = "ballerinax"
name = "vonage.verify"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
