[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Customer Relationship Management", "Cost/Freemium"]
org = "ballerinax"
name = "hubspot.crm.ticket"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
