[package]
license = ["Apache-2.0"]
keywords = ["The Movie DB", "TMDB", "Movies", "TV Shows"]
org = "ballerinax"
name = "themoviedb"
version = "0.1.2-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
