[package]
license = ["Apache-2.0"]
keywords = ["Support/Customer Support", "Cost/Paid"]
org = "ballerinax"
name = "xero.appstore"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
