[package]
license = ["Apache-2.0"]
keywords = ["HubSpot", "CRM", "feedback"]
org = "ballerinax"
name = "hubspot.crm.feedback"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
