[package]
license = ["Apache-2.0"]
keywords = ["Education/Elearning", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.classroom"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
