[package]
org = "ballerinax"
name = "nytimes.newswire"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Lifestyle & Entertainment/News & Lifestyle", "Cost/Free"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
