openapi: 3.0.0
servers:
  - url: http://api.nytimes.com/svc/news/v3
  - url: https://api.nytimes.com/svc/news/v3
info:
  description: >
    This is a generated connector for [New York Times Newswire API v3.0.0](https://developer.nytimes.com/docs/timeswire-product/1/overview) OpenAPI specification.

    With the Times Newswire API, you can get links and metadata for Times' articles as soon as they are published on NYTimes.com. 

    The Times Newswire API provides an up-to-the-minute stream of published articles. You can filter results by source (all, nyt, inyt) and section (arts, business, ...).
  termsOfService: http://developer.nytimes.com/tou
  title: Times Newswire API
  version: 3.0.0
  x-init-description: >
    The connector initialization requires setting the API credentials.
  
    Create a [NYTimes account](https://developer.nytimes.com/accounts/login) and obtain tokens following [this guide](https://developer.nytimes.com/get-started).
  x-apiClientRegistration:
    url: http://developer.nytimes.com/signup
  x-apisguru-categories:
    - media
    - open_data
  x-logo:
    url: https://static01.nyt.com/images/icons/t_logo_291_black.png
  x-origin:
    - format: openapi
      url: https://raw.githubusercontent.com/nytimes/public_api_specs/master/timeswire/timeswire_v3.json
      version: "3.0"
  x-providerName: nytimes.com
  x-serviceName: timeswire
externalDocs:
  url: http://developer.nytimes.com/
security:
  - apikey: []
paths:
  /content.json:
    get:
      operationId: getContents
      summary: Get articles.
      parameters:
        - description: The complete URL of a specific news item, URL-encoded or backslash-escaped
          in: query
          name: url
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  copyright:
                    type: string
                  num_results:
                    type: integer
                  results:
                    items:
                      $ref: "#/components/schemas/Article"
                    type: array
                  status:
                    type: string
                type: object
          description: An array of Articles
  "/content/{source}/{section}.json":
    get:
      operationId: filterContents
      summary: Filter articles by source and section.
      parameters:
        - description: |
            Limits the set of items by originating source

            all = items from both The New York Times and The International New York Times
            nyt = New York Times items only
            iht = International New York Times items only
          in: path
          name: source
          required: true
          schema:
            enum:
              - all
              - nyt
              - iht
            type: string
          x-consoleDefault: all
        - description: |
            Limits the set of items by one or more sections
            all | One or more section names, separated by semicolons

             To get all sections, specify all. To get a particular section or sections, use the section names returned by this request:
             http://api.nytimes.com/svc/news/v3/content/section-list.json
          in: path
          name: section
          required: true
          schema:
            type: string
          x-consoleDefault: all
        - description: Limits the number of results, between 1 and 20
          in: query
          name: limit
          required: false
          schema:
            default: 20
            type: integer
        - description: Sets the starting point of the result set
          in: query
          name: offset
          required: false
          schema:
            default: 0
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  copyright:
                    type: string
                  num_results:
                    type: integer
                  results:
                    items:
                      $ref: "#/components/schemas/Article"
                    type: array
                  status:
                    type: string
                type: object
          description: An array of Articles
  "/content/{source}/{section}/{time-period}.json":
    get:
      operationId: filterContentsByTime
      summary: Filter articles by source, section and time period.
      parameters:
        - description: |
            Limits the set of items by originating source

            all = items from both The New York Times and The International New York Times
            nyt = New York Times items only
            iht = International New York Times items only
          in: path
          name: source
          required: true
          schema:
            enum:
              - all
              - nyt
              - iht
            type: string
        - description: |
            Limits the set of items by one or more sections
            all | One or more section names, separated by semicolons

             To get all sections, specify all. To get a particular section or sections, use the section names returned by this request:
             http://api.nytimes.com/svc/news/v3/content/section-list.json
          in: path
          name: section
          required: true
          schema:
            type: string
        - description: Limits the set of items by time published, integer in number of hours
          in: path
          name: time-period
          required: true
          schema:
            type: integer
        - description: Limits the number of results, between 1 and 20
          in: query
          name: limit
          required: false
          schema:
            default: 20
            type: integer
        - description: Sets the starting point of the result set
          in: query
          name: offset
          required: false
          schema:
            default: 0
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                properties:
                  copyright:
                    type: string
                  num_results:
                    type: integer
                  results:
                    items:
                      $ref: "#/components/schemas/Article"
                    type: array
                  status:
                    type: string
                type: object
          description: An array of Articles
components:
  schemas:
    Article:
      properties:
        abstract:
          type: string
          nullable: true
        blog_name:
          type: string
          nullable: true
        byline:
          type: string
          nullable: true
        created_date:
          type: string
          nullable: true
        des_facet:
          items:
            type: string
          type: array
          nullable: true
        geo_facet:
          items:
            type: string
          type: array
          nullable: true
        headline:
          type: string
          nullable: true
        item_type:
          type: string
          nullable: true
        kicker:
          type: string
          nullable: true
        material_type_facet:
          type: string
          nullable: true
        multimedia:
          items:
            properties:
              caption:
                type: string
              copyright:
                type: string
              format:
                type: string
              height:
                type: integer
              subtype:
                type: string
              type:
                type: string
              url:
                type: string
              width:
                type: integer
            type: object
          type: array
          nullable: true
        per_facet:
          items:
            type: string
          type: array
          nullable: true
        published_date:
          type: string
          nullable: true
        related_urls:
          items:
            properties:
              suggested_link_text:
                type: string
                nullable: true
              url:
                type: string
                nullable: true
            type: object
          type: array
          nullable: true
        section:
          type: string
          nullable: true
        short_url:
          type: string
          nullable: true
        source:
          type: string
          nullable: true
        subsection:
          type: string
          nullable: true
        thumbnail_standard:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        updated_date:
          type: string
          nullable: true
        url:
          type: string
          nullable: true
      type: object
  securitySchemes:
    apikey:
      in: query
      name: api-key
      type: apiKey
      x-apikey-description: "Provide your API key as `api-key`. Eg: `{\"api-key\" : \"<API key>\"}`"
