[package]
license = ["Apache-2.0"]
keywords = ["covid19", "covid19 vaccine"]
org = "ballerinax"
name = "covid19"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
