[package]
license = ["Apache-2.0"]
keywords = ["Education/Elearning", "Cost/Paid"]
org = "ballerinax"
name = "clever.data"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
