[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/Search Engine Optimization", "Cost/Paid"]
org = "ballerinax"
name = "botify"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
