[package]
license = ["Apache-2.0"]
keywords = ["ebay", "analytics", "reporting"]
org = "ballerinax"
name = "ebay.analytics"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
