[package]
distribution = "slbeta6"
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Language Analysis", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.cloudnaturallanguage"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
