[package]
license = ["Apache-2.0"]
keywords = ["Finance/Billing", "Cost/Paid", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.cloudbuild"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
