[package]
org = "ballerinax"
name = "ebay.listing"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
license = ["Apache-2.0"]
keywords = ["ebay", "listing", "ecommerce"]

[build-options]
observabilityIncluded = true
