openapi: 3.0.1
info:
  x-ballerina-display:
    label: Fraudlabspro Smsverification
    iconPath: "resources/fraudlabspro.smsverification.svg"
  title: FraudLabs Pro SMS Verification
  description: >
    This is a generated connector for [FraudLabsPro SMS Verification API v1.0](https://www.fraudlabspro.com/developer/api/send-verification) OpenAPI specification.

    'Send an SMS with verification code and a custom message for authentication purpose. 
    
    It helps merchants to minimize chargebacks and fraud for various kinds of payment method, such as credit card, paypal, cod and so on. 
    
    Please visit https://www.fraudlabspro.com to learn more.'
  x-ballerina-init-description: >
    The connector initialization doesn't require setting the API credentials. 
  
    Create a [FraudLabsPro account](https://www.fraudlabspro.com/checkout) and obtain tokens following [this guide](https://www.fraudlabspro.com/developer/api/send-verification).

    Some operations may require passing the token as a parameter.
  version: '1.0'
servers:
  - description: Send an SMS with verification code and a custom message for authentication purpose.
    url: 'https://api.fraudlabspro.com'
  - description: Verify that an OTP sent by the Send SMS Verification API is valid.
    url: 'https://api.fraudlabspro.com'
paths:
  /v1/verification/send:
    post:
      description: Send an SMS with verification code and a custom message for authentication purpose.
      parameters:
        - name: country_code
          in: query
          description: 'ISO 3166 country code for the recipient mobile phone number. If parameter is supplied, then some basic telephone number validation is done.'
          schema:
            type: string
        - name: format
          in: query
          description: Returns the API response in json (default) or xml format.
          schema:
            type: string
            enum:
              - json
              - xml
        - name: tel
          in: query
          description: The recipient mobile phone number in E164 format which is a plus followed by just numbers with no spaces or parentheses.
          required: true
          schema:
            type: string
        - name: key
          in: query
          description: FraudLabs Pro API key.
          required: true
          schema:
            type: string
        - name: mesg
          in: query
          description: The message template for the SMS. Add <otp> as placeholder for the actual OTP to be generated. Max length is 140 characters.
          allowEmptyValue: true
          schema:
            type: string
      responses:
        '200':
          description: send verification response
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                '0':
                  value: '{"tran_id":"","credits_remaining":"0","error":""}'
  /v1/verification/result:
    get:
      description: Verify that an OTP sent by the Send SMS Verification API is valid.
      parameters:
        - name: tran_id
          in: query
          description: The unique ID that was returned by the Send Verification SMS API that triggered the OTP sms.
          required: true
          schema:
            type: string
        - name: key
          in: query
          description: FraudLabs Pro API key.
          required: true
          schema:
            type: string
        - name: format
          in: query
          description: Returns the API response in json (default) or xml format.
          schema:
            type: string
            enum:
              - json
              - xml
        - name: otp
          in: query
          description: The OTP that was sent to the recipientâ€™s phone.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get verification response
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples:
                '0':
                  value: '{"result":"","error":""}'
