[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRM", "Cost/Paid"]
org = "ballerinax"
name = "workday.absencemanagement"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
