[package]
license = ["Apache-2.0"]
keywords = ["zoom", "zoom meetings", "zoom webinars"]
org = "ballerinax"
name = "zoom"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.3.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
