openapi: 3.0.1
info:
  x-ballerina-display:
    label: Godaddy Aftermarket
    iconPath: "resources/godaddy.aftermarket.svg"
  title: GoDaddy Aftermarket API
  description: >-
    This is a generated connector for [GoDaddy Aftermarket API
    v1](https://developer.godaddy.com/doc/endpoint/aftermarket) OpenAPI
    specification. The GoDaddy Aftermarket API provides capability to access
    GoDaddy operations related to GoDaddy Auctions.
  version: v1
  x-ballerina-init-description: >-
    The connector initialization requires setting the API credentials.  Create a
    [GoDaddy Shoppers](https://sg.godaddy.com/) and obtain tokens by following
    [this guide](https://developer.godaddy.com/getstarted).  
servers:
  - url: //api.ote-godaddy.com/
tags:
  - name: v1
    description: ''
paths:
  /v1/aftermarket/listings:
    delete:
      tags:
        - v1
      summary: Remove listings from GoDaddy Auction
      operationId: deleteListings
      parameters:
        - name: domains
          in: query
          description: A comma separated list of domain names
          required: true
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            application/javascript:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            application/xml:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            text/javascript:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            text/xml:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
        '400':
          description: Request was malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication info not sent or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Authenticated user is not allowed access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: "\tRequired parameters must be specified in correct format"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests received within interval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            application/javascript:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            text/javascript:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            text/xml:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/aftermarket/listings/expiry:
    post:
      tags:
        - v1
      summary: Add expiry listings into GoDaddy Auction
      operationId: addExpiryListings
      requestBody:
        description: An array of expiry listings to be loaded
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AftermarketListingExpiryCreate'
          application/xml:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AftermarketListingExpiryCreate'
          text/xml:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AftermarketListingExpiryCreate'
        required: true
      responses:
        '200':
          description: Request was successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            application/javascript:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            application/xml:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            text/javascript:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
            text/xml:
              schema:
                $ref: '#/components/schemas/AftermarketListingAction'
        '400':
          description: Request was malformed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Authentication info not sent or invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '403':
          description: Authenticated user is not allowed access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '422':
          description: >-
            Required parameters must be specified in correct format<br>Too many
            Listings provided
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
        '429':
          description: Too many requests received within interval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            application/javascript:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            text/javascript:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
            text/xml:
              schema:
                $ref: '#/components/schemas/ErrorLimit'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
            application/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            application/xml:
              schema:
                $ref: '#/components/schemas/Error'
            text/javascript:
              schema:
                $ref: '#/components/schemas/Error'
            text/xml:
              schema:
                $ref: '#/components/schemas/Error'
      x-codegen-request-body-name: expiryListings
components:
  securitySchemes:
    ApiKeyAuth:       
      type: apiKey
      in: header  
      name: Authorization
      x-ballerina-apikey-description: "Provide your API Key as `Authorization`. Eg: {Authorization : sso-key [<API_KEY>]:[<API_SECRET>]}"
  schemas:
    AftermarketListingAction:
      required:
        - listingActionId
      type: object
      properties:
        listingActionId:
          type: integer
          description: Action Id
    AftermarketListingExpiryCreate:
      required:
        - domain
        - expiresAt
        - losingRegistrarId
      type: object
      properties:
        domain:
          type: string
          description: Domain name
        expiresAt:
          type: string
          description: Date when the domain expires
          format: iso-datetime
        losingRegistrarId:
          minimum: 1
          type: integer
          description: Losing registrar id for the domain
        pageViewsMonthly:
          type: integer
          description: Monthly traffic page view for the domain
        revenueMonthly:
          type: integer
          description: Monthly parking revenue (in USD micro unit) for the domain
    Error:
      required:
        - code
      type: object
      properties:
        code:
          type: string
          description: >-
            Short identifier for the error, suitable for indicating the specific
            error within client code
          format: constant
        fields:
          type: array
          description: >-
            List of the specific fields, and the errors found with their
            contents
          items:
            $ref: '#/components/schemas/ErrorField'
        message:
          type: string
          description: Human-readable, English description of the error
    ErrorField:
      required:
        - code
        - path
      type: object
      properties:
        code:
          type: string
          description: >-
            Short identifier for the error, suitable for indicating the specific
            error within client code
          format: constant
        message:
          type: string
          description: >-
            Human-readable, English description of the problem with the contents
            of the field
        path:
          type: string
          description: >-
            <ul>

            <li style='margin-left: 12px;'>JSONPath referring to a field
            containing an error</li>

            <strong style='margin-left: 12px;'>OR</strong>

            <li style='margin-left: 12px;'>JSONPath referring to a field that
            refers to an object containing an error, with more detail in
            `pathRelated`</li>

            </ul>
          format: json-path
        pathRelated:
          type: string
          description: >-
            JSONPath referring to a field containing an error, which is
            referenced by `path`
          format: json-path
    ErrorLimit:
      required:
        - code
        - retryAfterSec
      type: object
      properties:
        code:
          type: string
          description: >-
            Short identifier for the error, suitable for indicating the specific
            error within client code
          format: constant
        fields:
          type: array
          description: >-
            List of the specific fields, and the errors found with their
            contents
          items:
            $ref: '#/components/schemas/ErrorField'
        message:
          type: string
          description: Human-readable, English description of the error
        retryAfterSec:
          type: integer
          description: Number of seconds to wait before attempting a similar request
          format: integer-positive
    expiry:
      type: object
      properties:
        id:
          type: number
          format: double
