[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Freemium"]
org = "ballerinax"
name = "ably"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
