[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Reporting", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.youtube.reporting"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
 
[build-options]
observabilityIncluded = true
