openapi: 3.0.0
servers:
  - url: https://api.bintable.com/v1
info:
  x-ballerina-display:
    label: BINTable
    iconPath: "icon.png"
  contact:
    email: hello@bintable.com
  description: >
    This is the [BINTable API v1](https://bintable.com/get-api) OpenAPI Specification. 
    BIN lookup API, the free api service from bintable.com to lookup card information using it's BIN. 
    The service maintains updated database based on the comunity and other third party services to make sure all BINs in the database are accurate and up to date.
  x-ballerina-init-description: >
    The connector initialization doesn't require setting the API credentials.
    Create a [BINTable Account](https://bintable.com/get-api) and obtain the API key.
    Some operations may require passing the token as a parameter.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: BIN Lookup API
  version: 1.0.0-oas3
  x-apisguru-categories:
    - financial
  x-origin:
    - format: openapi
      url: https://bintable.com/api-files/openapi.json
      version: "3.0"
  x-providerName: bintable.com
tags:
  - description: Authorized users with API Key can call this service
    name: Lookup
  - description: Authorized users with API Key can call endpoints under this tag.
    name: Balance
paths:
  /balance:
    get:
      description: Get Account balance and expiry
      operationId: balanceLookup
      parameters:
        - description: The API key, which you can get from bintable.com website.
          explode: true
          in: query
          name: api_key
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ResponseItem"
          description: Balance reponse
        "401":
          description: Your balance is exhausted,or package expired
        "403":
          description: Invalid API Key
        "422":
          description: API key is missing
      summary: Check Balance
      tags:
        - Balance
  "/{bin}":
    get:
      description: |
        By passing in the appropriate BIN, you can lookup for
        card meta data in bintable.com API
      operationId: binLookup
      parameters:
        - description: pass the required BIN(Bank Identification Number) code
          explode: false
          in: path
          name: bin
          required: true
          schema:
            type: string
          style: simple
        - description: The API key, which you can get from bintable.com website.
          explode: true
          in: query
          name: api_key
          required: true
          schema:
            type: string
          style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseItem"
          description: BIN data response
        "401":
          description: Your balance is exhausted,or package expired
        "403":
          description: Invalid API Key
        "422":
          description: API key is missing
      summary: Lookup for bin
      tags:
        - Lookup
components:
  schemas:
    ResponseItem:
      properties:
        data:
          type: object
        message:
          example: SUCCESS
          type: string
        result:
          example: 200
          type: integer
      required:
        - data
        - message
        - result
      type: object
