[package]
license = ["Apache-2.0"]
keywords = ["Sales & CRM/Contact Management", "Cost/Freemium"]
org = "ballerinax"
name = "hubspot.crm.contact"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
