[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/File Management & Storage", "Cost/Paid"]
org = "ballerinax"
name = "files.com"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
