[package]
license = ["Apache-2.0"]
keywords = ["Azure", "Data Lake Storage", "big data"]
org = "ballerinax"
name = "azure.datalake"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.2-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
