[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Reporting", "Cost/Freemium"]
org = "ballerinax"
name = "avatax"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
