[package]
license = ["Apache-2.0"]
keywords = ["AI/Fine-tunes", "OpenAI", "Cost/Paid", "Files", "Models", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.finetunes"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.3"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
