[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.manufacturercenter"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/googleapis.manufacturercenter"
version = "1.5.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
