[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.manufacturercenter"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
