[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Security & Identity Tools", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.keyvault"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
