[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/Website Builders", "Cost/Freemium"]
org = "ballerinax"
name = "disqus"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
