[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Paid"]
org = "ballerinax"
name = "shopify.admin"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "2.3.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
