[package]
license = ["Apache-2.0"]
keywords = ["BitBucket", "Pull Request", "Repository"]
org = "ballerinax"
name = "bitbucket"
version = "0.2.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
