[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Source Control", "Cost/Freemium"]
org = "ballerinax"
name = "bitbucket"
icon = "icon.png"
distribution = "slbeta6"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
