[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Free"]
org = "ballerinax"
name = "optirtc.public"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
