[package]
org = "ballerinax"
name = "powertoolsdeveloper.files"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Apptigent","Powertools","Developer","developer_tools","datetime"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
