[package]
license = ["Apache-2.0"]
keywords = ["box api", "file", "folder", "freemium"]
org = "ballerinax"
name = "boxapi"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
