[package]
license = ["Apache-2.0"]
keywords = ["Box", "File", "Folder"]
org = "ballerinax"
name = "boxapi"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.0-SANPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
