[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Documents", "Cost/Paid"]
org = "ballerinax"
name = "alfresco"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/alfresco"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
