[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid"]
org = "ballerinax"
name = "saps4hana.itcm.user"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
