[package]
license = ["Apache-2.0"]
keywords = ["Education/Dictionary", "Cost/Freemium"]
org = "ballerinax"
name = "wordnik"
icon = "icon.png"
distribution = "2201.2.1"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
