[package]
license = ["Apache-2.0"]
keywords = ["Education/Dictionary", "Cost/Freemium"]
org = "ballerinax"
name = "wordnik"
icon = "icon.png"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
