[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "microsoft.dynamics365businesscentral"
icon = "icon.png"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
