[package]
org = "ballerinax"
name = "eventbrite"
icon = "icon.png"
version = "1.0.0"
distribution = "slbeta3"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Marketing/Event Management","Cost/Freemium"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
