[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Event Management", "Cost/Freemium"]
org = "ballerinax"
name = "eventbrite"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.3.1"
authors = ["Ballerina"]
