[package]
license = ["Apache-2.0"]
keywords = ["Business Management/ERP", "Cost/Paid"]
org = "ballerinax"
name = "saps4hana.itcm.customerhierarchy"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
