[package]
license = ["Apache-2.0"]
keywords = ["Website & App Building/App Builders", "Cost/Paid"]
org = "ballerinax"
name = "quickbase"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
