[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Artificial Intelligence", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.vision"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
