[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Artificial Intelligence", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.vision"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
