[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Documents", "Cost/Freemium"]
org = "ballerinax"
name = "figshare"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
