[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Documents", "Cost/Freemium"]
org = "ballerinax"
name = "figshare"
icon = "icon.png"
distribution = "2201.2.1"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
