openapi: 3.0.1
info:
  title: currencyapi
  description: This is a generated connector from [Cloudmersive](https://account.cloudmersive.com) OpenAPI specification.
  
    The Cloudmersive Currency APIs help you retrieve exchange rates and convert prices between currencies.
  x-init-description: >
    The connector initialization requires setting the API credentials.
    
    Create a [Cloudmersive account](https://account.cloudmersive.com/login) and obtain tokens following [this guide](https://account.cloudmersive.com/keys).
  version: v1
servers:
- url: https://testapi.cloudmersive.com/
paths:
  /currency/exchange-rates/list-available:
    post:
      tags:
      - CurrencyExchange
      summary: Get a list of available currencies and corresponding countries
      description: Enumerates available currencies and the countries that correspond
        to these currencies.
      operationId: Currency Exchange_Get Available Currencies
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableCurrencyResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/AvailableCurrencyResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/AvailableCurrencyResponse'
            text/xml:
              schema:
                $ref: '#/components/schemas/AvailableCurrencyResponse'
      security:
      - Apikey: []
  /currency/exchange-rates/convert/{source}/to/{destination}:
    post:
      tags:
      - CurrencyExchange
      summary: Converts a price from the source currency into the destination currency
      description: Automatically converts the price in the source currency into the
        destination currency using the latest available currency exchange rate data.
      operationId: Currency Exchange_Convert Currency
      parameters:
      - name: source
        in: path
        description: Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
        required: true
        schema:
          type: string
      - name: destination
        in: path
        description: Destination currency three-digit code (ISO 4217), e.g. USD, EUR,
          etc.
        required: true
        schema:
          type: string
      requestBody:
        description: Input price, such as 19.99 in source currency
        content:
          application/json:
            schema:
              type: number
              format: double
          text/json:
            schema:
              type: number
              format: double
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConvertedCurrencyResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ConvertedCurrencyResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/ConvertedCurrencyResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/ConvertedCurrencyResult'
      security:
      - Apikey: []
      x-codegen-request-body-name: sourcePrice
  /currency/exchange-rates/get/{source}/to/{destination}:
    post:
      tags:
      - CurrencyExchange
      summary: Gets the exchange rate from the source currency into the destination
        currency
      description: Automatically gets the exchange rate from the source currency into
        the destination currency using the latest available currency exchange rate
        data.
      operationId: Currency Exchange_Get Exchange Rate
      parameters:
      - name: source
        in: path
        description: Source currency three-digit code (ISO 4217), e.g. USD, EUR, etc.
        required: true
        schema:
          type: string
      - name: destination
        in: path
        description: Destination currency three-digit code (ISO 4217), e.g. USD, EUR,
          etc.
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResult'
            text/json:
              schema:
                $ref: '#/components/schemas/ExchangeRateResult'
            application/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateResult'
            text/xml:
              schema:
                $ref: '#/components/schemas/ExchangeRateResult'
      security:
      - Apikey: []
components:
  schemas:
    AvailableCurrencyResponse:
      type: object
      properties:
        Currencies:
          type: array
          description: List of available currencies from the API
          items:
            $ref: '#/components/schemas/AvailableCurrency'
      description: Result of performing an enumerate currencies operation
    AvailableCurrency:
      type: object
      properties:
        ISOCurrencyCode:
          type: string
          description: ISO 4217 currency three-letter code associated with the country
        CurrencySymbol:
          type: string
          description: Symbol associated with the currency
        CurrencyEnglishName:
          type: string
          description: Full name of the currency
        CountryName:
          type: string
          description: Name of the country
        CountryThreeLetterCode:
          type: string
          description: Three-letter ISO 3166-1 country code
        CountryISOTwoLetterCode:
          type: string
          description: Two-letter ISO 3166-1 country code
        IsEuropeanUnionMember:
          type: boolean
          description: True if this country is currently a member of the European
            Union (EU), false otherwise
      description: Details of a specific currency
    ConvertedCurrencyResult:
      type: object
      properties:
        ConvertedPrice:
          type: number
          description: The converted price in the destination currency
          format: double
        ISOCurrencyCode:
          type: string
          description: ISO 4217 currency three-letter code of destination price
        CurrencySymbol:
          type: string
          description: Destination currency symbol
        FormattedPriceAsString:
          type: string
          description: Formatted price in the destination currency as a string
      description: Result of performing a Convert Currency operation
    ExchangeRateResult:
      type: object
      properties:
        ExchangeRate:
          type: number
          description: The exchange rate from the source to the destination currency
          format: double
      description: Result of performing a get exchange rate operation
  securitySchemes:
    Apikey:
      type: apiKey
      x-apikey-description: "Provide your API Key as `Apikey`. Eg: `{\"Apikey\" : \"<API Key>}`\""
      description: API Key Authentication
      name: Apikey
      in: header
