[package]
license = ["Apache-2.0"]
keywords = ["Support/Customer Support", "Cost/Freemium"]
org = "ballerinax"
name = "pagerduty"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/pagerduty"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
