[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Cloud Services", "Cost/Free"]
org = "ballerinax"
name = "ip2whois"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
