[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Task Management", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.tasks"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
