[package]
license = ["Apache-2.0"]
keywords = ["Jira", "Projects", "Issues"]
org = "ballerinax"
name = "jira"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.3-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
