[package]
license = ["Apache-2.0"]
keywords = ["Communication/Video Conferncing", "Cost/Freemium"]
org = "ballerinax"
name = "livestorm"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "2.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
