[package]
license = ["Apache-2.0"]
keywords = ["LiveStorm", "Event", "Webinar"]
org = "ballerinax"
name = "livestorm"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.1.2-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
