[package]
license = ["Apache-2.0"]
keywords = ["world bank", "world bank indicators"]
org = "ballerinax"
name = "worldbank"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.7.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
