[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Social Media Marketing", "Cost/Freemium"]
org = "ballerinax"
name = "ritekit"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
