[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Project Management", "Cost/Paid"]
org = "ballerinax"
name = "xero.projects"
icon = "icon.png"
distribution = "2201.4.1"
version = "1.4.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
