[package]
license = ["Apache-2.0"]
keywords = ["Finance/Payment", "Cost/Freemium"]
org = "ballerinax"
name = "paypal.orders"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.5.0"
authors = ["Ballerina"]
