[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Images And Design", "Cost/Paid"]
org = "ballerinax"
name = "logoraisr"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
