[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Data Ingestion", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.cloudpubsub"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
