openapi: 3.0.1
info:
  title: Unit of Measure Service
  description: >
    This is [SAPS4HANA Intelligent Trade Claims Management API v1.0.0](https://help.sap.com/viewer/902b9d277dfe48fea582d28849d54935/CURRENT/en-US) OpenAPI specification. 
    The unit of measure service allows you to load units of measure for various purposes in SAPS4HANA Intelligent Trade Claims Management.
  x-ballerina-init-description: >
    Create and configure an OAuth2 client credentials by following [this guide](https://help.sap.com/viewer/b865ed651e414196b39f8922db2122c7/LATEST/en-US/7aefa21a65f94b25b7e639c3931b6f83.html).
  x-ballerina-display:
    label: SAPS4HANA ITCM Unit of Measure
    iconPath: "icon.png"
  license:
    name: SAP
  version: 1.0.0
externalDocs:
  description: Business Documentation for Unit of Measure Service
  url: https://help.sap.com/viewer/902b9d277dfe48fea582d28849d54935/CURRENT/en-US/5e09d4c1178148899a0b6f91c632208e.html
security:
- OAuth2: []
tags:
- name: Unit of Measure
paths:
  /uom:
    post:
      tags:
      - Unit of Measure
      summary: Create a new Unit of Measure
      description: Using this API, user can create a Unit of Measure. As of now, batch creation is not supported
      operationId: createUoM
      requestBody:
        description: Request payolad to create a new Unit of Measure
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UoMStoreDTO'
        required: true
      responses:
        '201':
          description: Success Created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUoMMessage'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUnauthorizedMessage'
        '403':
          description: Forbidden (insufficient authorization).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseForbiddenMessage'
      deprecated: false
      security:
      - OAuth2: []
  /uom/{isocode}/{languageKey}:
    get:
      tags:
      - Unit of Measure
      summary: Get Unit of Measure
      description: Using this api, user can get a particular Unit of Measure using {isocode} and {languageKey}
      operationId: getByISOLangKey
      parameters:
      - name: isocode
        in: path
        description: Isocode
        required: true
        schema:
          maxLength: 3
          minLength: 0
          type: string
      - name: languageKey
        in: path
        description: LanguageKey
        required: true
        schema:
          maxLength: 2
          minLength: 0
          type: string
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UoMResponseDTO'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUnauthorizedMessage'
        '403':
          description: Forbidden (insufficient authorization).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseForbiddenMessage'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseNotFoundMessage'
      deprecated: false
      security:
      - OAuth2: []
    delete:
      tags:
      - Unit of Measure
      summary: Delete Unit of Measure
      description: Using this api, user can get a particular Unit of Measure using {isocode} and {languageKey}
      operationId: deleteByISOLangKey
      parameters:
      - name: isocode
        in: path
        description: Isocode
        required: true
        schema:
          maxLength: 3
          minLength: 0
          type: string
      - name: languageKey
        in: path
        description: LanguageKey
        required: true
        schema:
          maxLength: 2
          minLength: 0
          type: string
      responses:
        '200':
          description: OK.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUoMMessage'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseUnauthorizedMessage'
        '403':
          description: Forbidden (insufficient authorization).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseForbiddenMessage'
        '404':
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseNotFoundMessage'
      deprecated: false
      security:
      - OAuth2: []
components:
  schemas:
    ResponseDeleteAll:
      title: ResponseDeleteAll
      type: object
      properties:
        count:
          type: integer
          format: int32
        message:
          type: string
        timestamp:
          type: string
          format: date-time
    ResponseMessage:
      title: ResponseMessage
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        uri:
          type: string
    ResponseNotFoundMessage:
      type: object
      example:
        message: There is no data found based on the given inputs.
        error: No Result Found
        timestamp: '2021-01-18T19:37:13.701+00:00'
      properties:
        message:
          type: string
        error:
          type: string
        timestamp:
          type: string
          format: date-time
      title: Not Found Message
    ResponseForbiddenMessage:
      type: object
      example:
        message: Access denied
        timestamp: '2021-01-18T18:33:18.914Z'
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        uri:
          type: string
      title: Forbidden Message
    ResponseUnauthorizedMessage:
      type: object
      example:
        message: Unauthorized/API key not found
        timestamp: '2021-01-18T18:33:18.914Z'
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        uri:
          type: string
      title: Unauthorized Message
    ResponseUoMMessage:
      title: ResponseUoMMessage
      type: object
      example:
        languageKey: EN
        unitOfMeasureISO: T006I
        message: Success created
        timestamp: '2021-01-18T18:33:18.914Z'
      properties:
        langKey:
          type: string
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        unitOfMeasureISO:
          type: string
    UoMResponseDTO:
      title: UoMResponseDTO
      type: object
      properties:
        languageKey:
          type: string
          example: EN
        unitDescription:
          type: string
          example: Units of Measurement
        unitText:
          type: string
          example: T006J
    UoMStoreDTO:
      title: UoMStoreDTO
      type: object
      example:
        businessSystem: '0'
        unitOfMeasureCode: T006
        unitOfMeasureCodeISO: T006I
        unitText: T006J
        unitDescription: Units of Measurement
        languageKey: EN
        numberOfDecimals: 2
      properties:
        businessSystem:
          type: string
        languageKey:
          type: string
        numberOfDecimals:
          type: integer
          format: int32
        unitDescription:
          type: string
        unitOfMeasureCode:
          type: string
        unitOfMeasureCodeISO:
          type: string
        unitText:
          type: string
    UoMStoreResponse:
      title: UoMStoreResponse
      type: object
      properties:
        message:
          type: string
        timestamp:
          type: string
          format: date-time
        uomStoreData:
          type: array
          items:
            $ref: '#/components/schemas/UoMStoreDTO'
  securitySchemes:
    OAuth2:
      type: oauth2
      description: To use this API, you need to get OAuth client credentials (client ID, secret, and geolocation) from SAP ITCM, and be authorized to use the relevant scope. Refer to the <a href="https://developer.sap.com/api-reference/authentication/getting-started.html">full authentication information</a> for more information.
      flows:
        clientCredentials:
          tokenUrl: https://colgate-dev1.authentication.us30.hana.ondemand.com/oauth/token
          scopes: {}
x-sap-shortText: The Unit of Measure service represent unit of measure that can be posted to, deleted or queried from SAP Intelligent Trade Claims Management by a user.