[package]
license = ["Apache-2.0"]
keywords = ["Content & Files/Documents", "Cost/Freemium"]
org = "ballerinax"
name = "edocs"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]
icon = "icon.png"

[build-options]
observabilityIncluded = true