[package]
license = ["Apache-2.0"]
keywords = ["Medium", "Publication"]
org = "ballerinax"
name = "medium"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "0.2.4-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
