[package]
license = ["Apache-2.0"]
keywords = ["AI/Chat", "OpenAI", "Cost/Paid", "GPT-3.5", "ChatGPT", "Vendor/OpenAI"]
org = "ballerinax"
name = "openai.chat"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/openai.chat"
version = "1.0.4"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
