[package]
license = ["Apache-2.0"]
keywords = ["Business Intelligence/Analytics", "Cost/Freemium"]
org = "ballerinax"
name = "hubspot.analytics"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "2.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
