[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Enterprise Architecture Tools", "Cost/Paid"]
org = "ballerinax"
name = "leanix.integrationapi"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/openapi-connectors/tree/main/openapi/leanix.integrationapi"
version = "1.5.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
