[package]
license = ["Apache-2.0"]
keywords = ["IT Operations/Geographic Information Systems", "Cost/Freemium"]
org = "ballerinax"
name = "geonames"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
