[package]
license = ["Apache-2.0"]
keywords = ["Finance/Payment", "Cost/Paid"]
org = "ballerinax"
name = "nowpayments"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
