[package]
org = "ballerinax"
name = "azure.sqldb"
icon = "icon.png"
version = "1.0.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["IT Operations/Databases","Cost/Paid","Vendor/Microsoft"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true
