openapi: 3.0.1
servers:
  - description: FraudLabs Pro
    url: https://api.fraudlabspro.com
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/fraudlabspro/fraudlabspro/1.0
info:
  contact:
    x-twitter: fraudlabspro
  title: FraudLabs Pro Fraud Detection
  version: "1.1"
  description: >
    This is a generated connector for [FraudLabsPro Fraud Detection API v1.1](https://www.fraudlabspro.com/developer/api/screen-order) OpenAPI specification.

    Online payment fraud detection service. It helps merchants to minimize chargebacks and therefore maximize the revenue. 

    It can be used to detect fraud for various kinds of payment method, such as credit card, paypal, cod and so on. 
    
    Please visit https://www.fraudlabspro.com to learn more.
  x-init-description: >
    The connector initialization doesn't require setting the API credentials. 
  
    Create a [FraudLabsPro account](https://www.fraudlabspro.com/checkout) and obtain tokens following [this guide](https://www.fraudlabspro.com/developer/api/screen-order).

    Some operations may require passing the token as a parameter.
  x-apisguru-categories:
    - ecommerce
  x-logo:
    url: https://twitter.com/fraudlabspro/profile_image?size=original
  x-origin:
    - converter:
        url: https://github.com/lucybot/api-spec-converter
        version: 2.7.31
      format: openapi
      url: https://app.swaggerhub.com/apiproxy/schema/file/fraudlabspro/fraudlabspro-fraud-detection/1.1/swagger.json
      version: "3.0"
  x-providerName: fraudlabspro.com
  x-serviceName: fraud-detection
paths:
  /v1/order/feedback:
    post:
      summary: Feedback the status of an order transaction.
      description: Feedback the status of an order transaction.
      parameters:
        - in: query
          name: id
          description: Unique transaction Id generated by Fraud Check API. 
          required: true
          schema:
            type: string
        - in: query
          name: key
          description: API license key
          required: true
          schema:
            type: string
        - in: query
          name: format
          description: Return the result in json or xml format. Default:xml
          schema:
            enum:
              - json
              - xml
            type: string
        - in: query
          name: action
          description: Perform APPROVE, REJECT, or REJECT_BLACKLIST action to transaction
          required: true
          schema:
            enum:
              - APPROVE
              - REJECT
              - REJECT_BLACKLIST
            type: string
        - allowEmptyValue: true
          in: query
          name: notes
          description: Notes for the feedback request
          schema:
            type: string
      responses:
        "200":
          content:
            application/json; charset=utf-8:
              examples:
                "0":
                  value: '{"fraudlabspro_error_code":"","fraudlabspro_message":""}'
              schema:
                type: string
          description: Feedback order response
  /v1/order/screen:
    post:
      summary: Screen order for payment fraud.
      description: Screen order for payment fraud.
      parameters:
        - in: query
          name: ip
          description: IP address of online transaction. It supports both IPv4 and IPv6 address format
          required: true
          schema:
            type: string
        - in: query
          name: key
          description: API license key
          required: true
          schema:
            type: string
        - in: query
          name: format
          description: Return the result in json or xml format
          schema:
            enum:
              - json
              - xml
            type: string
        - allowEmptyValue: true
          in: query
          name: last_name
          description: User's last name
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: first_name
          description: User's first name
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bill_addr
          description: Street address of billing address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bill_city
          description: City of billing address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bill_state
          description: State of billing address. It supports state codes, e.g. NY (New York), for state or province of United States or Canada. Please refer to state & province codes for complete list. 
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bill_country
          description: Country of billing address. It requires the input of ISO-3166 alpha-2 country code, e.g. US for United States. Please refer to Country Codes for complete list. 
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bill_zip_code
          description: Postal or ZIP code of billing address.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: ship_addr
          description: Street address of shipping address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: ship_city
          description: City of shipping address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: ship_state
          description: State of shipping address. It supports state codes, e.g. NY - New York, for state or province of United States or Canada. Please refer to state & province codes for complete list. 
          schema:
            type: string
        - in: query
          name: ship_country
          description: Country of shipping address. It requires the input of ISO-3166 alpha-2 country code, e.g. US for United States. Please refer to Country Codes for complete list. 
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: ship_zip_code
          description: Postal or ZIP code of shipping address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: email_domain
          description: Domain name of email address. For example, the domain of email address support@fraudlabspro.com is fraudlabspro.com. If you didn't supply this value, the system will automatically extract the domain name from the email field.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: user_phone
          description: User's phone number
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: email
          description: User's email address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: email_hash
          description: SHA1-64k hash of user's email address
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: username_hash
          description: SHA1-64k hash of user's username
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: password_hash
          description: SHA1-64k hash of user's password
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: bin_no
          description: First 6-9 digits of credit card number to identify issuing bank
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: card_hash
          description: SHA1-64k hash of credit number
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: avs_result
          description: The single character AVS result returned by the credit card processor
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: cvv_result
          description: The single character CVV2 result returned by the credit card processor
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: user_order_id
          description: Merchant identifier to uniquely identify a transaction. It supports maximum of 15 characters user order id input.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: user_order_memo
          description: Merchant description of an order transaction. It supports maximum of 200 characters.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: amount
          description: Amount of the transaction
          schema:
            type: number
        - allowEmptyValue: true
          in: query
          name: quantity
          description: Total quantity of the transaction
          schema:
            type: integer
        - allowEmptyValue: true
          in: query
          name: currency
          description: Currency code used in the transaction. It requires the input of ISO-4217 (3 characters) currency code, e.g. USD for US Dollar.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: department
          description: Merchant identifier to uniquely identify a product or service department.
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: payment_mode
          description: Payment mode of transaction
          schema:
            type: string
        - allowEmptyValue: true
          in: query
          name: flp_checksum
          description: Checksum for the device validation
          schema:
            type: string
      responses:
        "200":
          content:
            application/json; charset=utf-8:
              examples:
                "0":
                  value: '{"is_country_match":"","is_high_risk_country":"","distance_in_km":"-","distance_in_mile":"-","ip_country":"","ip_continent":"","ip_region":"","ip_city":"","ip_latitude":"","ip_longitude":"","ip_timezone":"","ip_elevation":"","ip_domain":"","ip_mobile_mnc":"","ip_mobile_mcc":"","ip_mobile_brand":"","ip_netspeed":"","ip_isp_name":"","ip_usage_type":"","is_free_email":"","is_new_domain_name":"","is_domain_exists":"","is_proxy_ip_address":"","is_bin_found":"","is_bin_country_match":"","is_bin_name_match":"","is_bin_phone_match":"","is_bin_prepaid":"","is_address_ship_forward":"NA","is_bill_ship_city_match":"","is_bill_ship_state_match":"","is_bill_ship_country_match":"","is_bill_ship_postal_match":"","is_ship_address_blacklist":"","is_phone_blacklist":"","is_ip_blacklist":"","is_email_blacklist":"","is_credit_card_blacklist":"","is_device_blacklist":"","is_user_blacklist":"","is_high_risk_username_password":"","is_export_controlled_country":"","is_malware_exploit":"","user_order_id":"","user_order_memo":"","fraudlabspro_score":0,"fraudlabspro_distribution":0,"fraudlabspro_status":"","fraudlabspro_id":"NA","fraudlabspro_version":"1.5.0","fraudlabspro_error_code":"","fraudlabspro_message":"","fraudlabspro_credits":"0"}'
              schema:
                type: string
          description: Screen order response
