openapi: 3.0.1
info:
  x-ballerina-display:
    label: Shipwire Carrier
    iconPath: "icon.png"
  title: Shipwire Carrier API
  description: |
    This is a generated connector for [Shipwire Carrier API v3.0](https://www.shipwire.com/developers/carrier/) OpenAPI specification.
    The Carriers API is used to manage supported carriers and their respective capabilities. 
    Use it to view, add or remove carriers enabled to function with Shipwire and Shipwire Anywhere warehouses.
  x-ballerina-init-description: >
    The connector initialization requires setting the API credentials. 
    Create a [Shipwire account](https://www.shipwire.com) and obtain tokens by following [this guide](https://www.shipwire.com/developers/getting-started).
  version: "3.0"
servers:
- url: https://api.shipwire.com/
security:
- basicAuth: []
paths:
  /api/v3.1/carriers:
    get:
      tags:
      - Carrier
      summary: Get carriers availability
      description: Get carriers information
      operationId: GetCarriers
      parameters:
      - name: name
        in: query
        description: Add description
        schema:
          type: string
      - name: carrierCode
        in: query
        description: Add description
        schema:
          type: string
      - name: serviceLevelCode
        in: query
        description: Add description
        schema:
          type: string
      - name: isPoBoxSupported
        in: query
        description: Add description
        schema:
          type: string
      responses:
        200:
          description: "Carriers response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCarriersResponse'
  /api/v3.1/carriers/{id}:
    get:
      tags:
      - Carrier
      summary: Get carrier availability
      description: Get carrier information
      operationId: GetCarrier
      parameters:
      - name: id
        in: path
        description: The prefix concatenated with '-' and service level code of the
          carrier.
        required: true
        schema:
          type: string
      responses:
        200:
          description: "Carrier response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetCarrierResponse'
components:
  schemas:
    CarrierServerResponse:
      title: Receiving Server Response
      type: object
      properties:
        status:
          type: integer
          description: This is the HTTP status code.
          example: 200
        message:
          type: string
          description: This is the HTTP status message.
          example: Successful
        resourceLocation:
          type: string
          description: A URL that gives more information about the linked resource.
            A 'null' value would mean that no further information is available for
            that resource. Use this resource to get detailed information about the
            carrier.
          example: https://api.shipwire.com/api/v3.1/carriers?offset=0&limit=20&expand=all
      description: Receiving Server Response
    GetCarriersResponse:
      allOf:
      - $ref: '#/components/schemas/CarrierServerResponse'
      - title: Get Carriers Response
        type: object
      - type: object
        description: Get Carriers Response
      - type: object
    GetCarrierResponse:
      allOf:
      - $ref: '#/components/schemas/CarrierServerResponse'
      - title: Get Carriers Response
        type: object
      - type: object
        description: Get Carriers Response
      - type: object
    CarriersPaginationModel:
      title: CarriersPaginationModel
      type: object
      properties:
        offset:
          type: integer
          description: This is an integer that matches the offset given in the request
            and dictates the number of items to skip while fetching results. For example,
            there is a preset limit of 20 results per page. If there are 30 total
            results and offset is set to 20, then the response will show the second
            "page" of results, with items 21 to 30.
          example: 0
        total:
          type: integer
          description: Total number of available items in the API response.
          example: 164
        previous:
          type: string
          description: A link used to fetch the previous set or page of items in the
            API response.
          example: null
        next:
          type: string
          description: A link used to fetch the next set or page of items in the API
            response.
          example: https://api.shipwire.com/api/v3.1/carriers?offset=20&limit=20
        items:
          type: array
          items:
            $ref: '#/components/schemas/CarrierResourceModel'
    CarrierResourceModel:
      title: CarrierResourceModel
      type: object
      properties:
        resourceLocation:
          type: string
          description: A URL that gives more information about the linked resource.
            A null value would mean that no further information is available for that
            resource. Use this resource to get detailed information about the carrier.
          example: https://api.shipwire.com/api/v3.1/carriers/ASND-EPSZ
        resource:
          $ref: '#/components/schemas/CarrierModel'
    CarrierModel:
      title: CarrierModel
      type: object
      properties:
        code:
          type: string
          description: A string consisting of carrier code and service level.
          example: FDX GD
        serviceLevelCode:
          type: string
          description: This is the service level code associated with the carrier.
            There are multiple levels for one type of service. Each level has a specific
            code. (e.g. For FDX the codes are 1D, 2D, GD, etc.)
          example: EPSZ
        name:
          type: string
          description: This is the name of the associated carrier.
          example: Asendia ePacket Tracked
        isFreightCarrier:
          type: integer
          description: A boolean that indicates the carrier is a freight carrier.
            The value 1 (True) means this carrier supports heavy weight orders or
            large items.
          format: enum
          example: 1
        isRestrictedCarrier:
          type: integer
          description: A boolean that indicates whether or not the carrier is restricted.
            The value 1 (True) means this carrier is not available for general use.
            If required, contact customer care for possible enablement.
          format: enum
          example: 0
        isPostalCarrier:
          type: integer
          description: A boolean that indicates the carrier uses a national government
            postal service, either for aggregated or for last mile delivery.
          format: enum
          example: 1
        isTerritorySupported:
          type: integer
          description: A boolean that indicates if the carrier supports US territories.
            (e.g. Puerto Rico, Guam, etc.)
          format: enum
          example: 1
        isPoBoxSupported:
          type: integer
          description: A boolean that indicates if the carrier supports PO box delivery.
          format: enum
          example: 0
        isApoFpoSupported:
          type: integer
          description: A boolean that indicates the carrier supports delivery to military
            addresses (APO, FPO).
          format: enum
          example: 1
        isPickupRequired:
          type: integer
          description: A boolean that indicates the carrier requires pickup. A 0 (False)
            value would mean that the carrier supports delivery to doorstep. This
            feature is related to third party carriers.
          format: enum
          example: 1
        isSignatureRequired:
          type: integer
          description: A boolean that indicates the carrier requires a signature upon
            delivery of the order.
          format: enum
          example: 0
        isSelfInsured:
          type: integer
          description: A boolean that indicates the carrier is self-insured for damages
            that occur to an order while in transit.
          format: enum
          example: 1
        isDangerousGoodsSupported:
          type: integer
          description: A boolean that indicates the carrier can transport orders that
            include dangerous goods. (e.g. chemicals, etc.)
          format: enum
          example: 1
        isTrackable:
          type: integer
          description: A boolean that indicates orders transported by the carrier
            will recieive a tracking ID so that it can be tracked after leaving the
            warehouse through to delivery.
          format: enum
          example: 0
        isMediaSupported:
          type: integer
          description: A boolean that indicates the carrier provides special services
            specific to the handling of media. (e.g. books, videotapes, DVDs, CDs,
            printed music and other sound recordings)
          format: enum
          example: 1
        minimumShippingDays:
          type: integer
          description: The minimum number of days the carrier takes for shipping the
            order.
          example: 7
        maximumShippingDays:
          type: integer
          description: The maximum number of days the carrier takes for shipping the
            order.
          example: 14
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
