[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRMS", "Cost/Paid"]
org = "ballerinax"
name = "zoho.people"
icon = "icon.png"
distribution = "2201.4.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.3.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
