[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/Books", "Cost/Freemium", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.books"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.1-SNAPSHOT"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
