[package]
org = "ballerinax"
name = "googleapis.discovery"
version = "0.1.0-SNAPSHOT"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["google","api","discovery", "cloud"]
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"

[build-options]
observabilityIncluded = true