[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Ads & Conversion", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.discovery"
icon = "icon.png"
distribution = "2201.2.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.4.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
