[package]
license = ["Apache-2.0"]
keywords = ["Marketing/Social Media Accounts", "Cost/Free"]
org = "ballerinax"
name = "instagram"
icon = "icon.png"
distribution= "slbeta3"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.0.0"
authors = ["Ballerina"]

[build-options]
observabilityIncluded = true
