[package]
license = ["Apache-2.0"]
keywords = ["Productivity/Task Management", "Cost/Freeemium"]
org = "ballerinax"
name = "trello"
icon = "icon.png"
distribution = "2201.0.0"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.1.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
