[package]
license = ["Apache-2.0"]
keywords = ["Internet of Things/Device Management", "Cost/Paid", "Vendor/Microsoft"]
org = "ballerinax"
name = "azure.timeseries"
icon = "icon.png"
distribution = "slbeta6"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.0"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
